### ISSUE TITLE
Can't resolve composed CSS from node_modules folder

### ISSUE THREAD

**Issue by 0xR** [jacobp100/es-css-modules#1]
I have CSS which look like this:
```css
.button {
  composes: btn from 'basscss-btn';
}
```

I get the error:
```
{ Error: ENOENT: no such file or directory, open '/project/src/basscss-btn-primary'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/project/src/basscss-btn-primary' }
```

While it should be resolving `node_modules/basscss-btn/index.css`.

I tried using the `resolveOptions` but it seems to only be used to resolve JS imports and not composed CSS modules.

**Comment by jacobp100** [comment]
After digging around, I think [you’re meant to](https://github.com/css-modules/css-modules-loader-core/blob/master/test/test-cases/compose-node-module/source.css) specify the css file you want: `basscss-btn/index.css` in this case. Let me know how that goes!

**Comment by 0xR** [comment]
Thanks I'll try that. But it would be cool though if I could specify resolve options to do this automatically.

I just remembered I tweaked my webpack config to get it to work there:

``` js
    new webpack.ResolverPlugin(
      new webpack.ResolverPlugin.FileAppendPlugin(['/index.css'])
    ),
```

So it does make sense that this doesn't work automatically for es-css-modules.

**Comment by 0xR** [comment]
Tried it, but now I get another error for:

``` css
  composes: btn-primary from 'basscss-btn-primary/index.css';
```

```
Error: Class name btn-primary is invalid
```

Which is hard to fix, since I don't control the naming of basscss. I don't consider this an edge case since dash-casing is default for css.

**Comment by jacobp100** [comment]
This seemed to work for me ([test](https://github.com/jacobp100/es-css-modules/blob/master/test/index.js#L261)). You’re only meant to run your own files through, and not basscss’s. Does that fix anything?

**Comment by 0xR** [comment]
I am running on my own files. In my file it looks like this:

``` css
.primary {
  composes: btn-primary from 'basscss-btn-primary';
}
```

I can post a repro tomorrow.

**Comment by jacobp100** [comment]
Okay, I should have fixed that bug in version `1.2.4`.

**Comment by 0xR** [comment]
For some reason I can't reproduce it anymore. I do have some more question, maybe we should use some chat.

**Comment by jacobp100** [comment]
Sure, you can DM me on Twitter if that works best ([@jacobp100](https://twitter.com/jacobp100)).
